apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: bitcoin
  name: bitcoin
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        service: bitcoin
    spec:
      containers:
        image: ruimarinho/bitcoin-core
        name: bitcoin
        volumeMounts:
          - mountPath: /home/bitcoin/.bitcoin
            name: bitcoin-data
      restartPolicy: Always
      volumes:
        - name: bitcoin-data
          persistentVolumeClaim:
            claimName: nfs-persistent-volume-claim-btc
