apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc
  labels:
    app: btc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc
  template:
    metadata:
      labels:
        app: btc
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
        - name: copy-bitcoind-config
          image: busybox
          command: ["rm", "/bitcoin/.lock"]
          volumeMounts:
            - name: btcdata
              mountPath: /bitcoin
      containers:
        - name: btc-cont
          image: tthebst/btc:latest
          ports:
            - containerPort: 8333
            - containerPort: 8332
          volumeMounts:
            - mountPath: /bitcoin
              name: btcdata
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sudo rm /bitcoin/.lock"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: btcdata
          hostPath:
            # directory location on host
            path: /home/pi/localfs
