apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-persistent-volume-claim-btc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 400Gi
