apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - /usr/bin/curl -Is https:/www.stockbuilder.tk | grep 200 || echo "The site is down" | /usr/bin/mail -v -s "Site is down(stockbuilder.tk)" gretler.tim@gmail.com
                - /usr/bin/curl -Is https:/www.timgretler.ch | grep 200 || echo "The site is down" | /usr/bin/mail -v -s "Site is down(timgretler.ch)" gretler.tim@gmail.com
                - /usr/bin/curl -Is https://www.speechgroup.ch  | grep 200 || echo "The site is down" | /usr/bin/mail -v -s "Site is down(speechgroup.ch)" gretler.tim@gmail.com
                - /usr/bin/curl -Is https:/www.stockbuilder123.ch| grep 200 || echo "The site is down" | /usr/bin/mail -v -s "Site is down(stockbuilder.ch)" gretler.tim@gmail.com
          restartPolicy: OnFailure
