apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: www.stockbuilder123.tk
      http:
        paths:
        - path: /
          backend:
            serviceName: stocksservice
            servicePort: http
    - host: stockbuilder123.tk
      http:
        paths:
        - path: /
          backend:
            serviceName: stocksservice
            servicePort: http
    - host: www.speechrecognition.tk
      http:
        paths:
        - path: /
          backend:
            serviceName: groupproject-service
            servicePort: http
    - host: speechrecognition.tk
      http:
        paths:
        - path: /
          backend:
            serviceName: groupproject-service
            servicePort: http