apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: www.stockbuilder123.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: stocksservice
              servicePort: http
    - host: stockbuilder123.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: stocksservice
              servicePort: http
    - host: www.speechgroup.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: groupproject-service
              servicePort: http
    - host: speechgroup.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: groupproject-service
              servicePort: http
    - host: www.timgretler.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: mywebsite-service
              servicePort: http
    - host: timgretler.ch
      http:
        paths:
          - path: /
            backend:
              serviceName: mywebsite-service
              servicePort: http
