apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-btc
  labels:
    type: local
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mydisk"

