
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: kube-system
data:
  traefik.toml: |
      defaultEntryPoints = ["http", "https"]
        [entryPoints]
          [entryPoints.http]
          address = ":80"
            [entryPoints.http.redirect]
            entryPoint = "https"
          [entryPoints.https]
          address = ":443"
            [entryPoints.https.tls]
      [acme]
      email = "gretler.tim@gmail.com"
      storage = "acme.json"
      onHostRule = true
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      entryPoint = "https"
        [acme.dnsChallenge]
          provider = "cloudflare"
          delayBeforeCheck = 0
      [[acme.domains]]
        main = "stockbuilder123.tk"
      [[acme.domains]]
        main = "speechrecognition.tk"