---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-configmap
      containers:
        - image: traefik:1.7
          name: traefik-ingress-lb
          volumeMounts:
            - mountPath: "/config"
              name: "config"
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
          env:
            - name: CF_API_EMAIL_FILE
              valueFrom:
                secretKeyRef:
                  name: cloudfare-dns
                  key: username.txt
            - name: CF_API_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: cloudfare-dns
                  key: api_token.txt
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudfare-dns
                  key: username.txt
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudfare-dns
                  key: api_token.txt
          args:
            - --configfile=/config/traefik.toml
            - --api
            - --kubernetes
            - --logLevel=INFO
