apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btc
spec:
  selector:
    matchLabels:
      app: btc
  serviceName: "btc"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: btc
    spec:
      containers:
      - name: btc
        image: kylemanna/bitcoind:latest
        ports:
        - containerPort: 8333
        - containerPort: 8332
        volumeMounts:
        - name: www
          mountPath: /mnt/mydisk
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-bitcoin-class"
      resources:
        requests:
          storage: 300Gi
